[package]
name = "mine_status"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
askama = "0.11"
axum = "0.6.0-rc.2"
kdl = "4.3"
tokio = { version = "1.21", features = ["full"] }
